name: counter_13
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  path: ^1.8.3
  get: ^4.7.2
  smooth_page_indicator: ^1.2.1
  dotlottie_loader: ^0.0.4
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pushup.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/pushup.jpg"

dependency_overrides:
  web: 0.5.0
  flutter_lints: ^2.0.0
  path: 1.8.3

flutter:
  uses-material-design: true
  assets:
    - assets/